packages = ["https://raw.githubusercontent.com/premodernitalia/deck-recognizer/main/PyTrie-0.4.0-py3-none-any.whl"]

[[fetch]]
files = ["./data.py", "./deck.py", "./deck_parser.py", "./deck_export.py"]

[splashscreen]
enabled = false